{
  "formatVersion": "1.1",
  "component": {
    "group": "com.apollographql.ktor",
    "module": "apollo-engine-ktor",
    "version": "0.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "com.apollographql.apollo",
          "module": "apollo-runtime",
          "version": {
            "requires": "4.1.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-websockets",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "apollo-engine-ktor-metadata-0.1.2-SNAPSHOT.jar",
          "url": "apollo-engine-ktor-0.1.2-SNAPSHOT.jar",
          "size": 8612,
          "sha512": "2e17e8e6f19a8be23db9366a93d2f7be510cba55376f3c5adc9332af684e5d55fb05c2ad1754d7f3ebbd1496ac58ecd8ed4a1efb946718e444766b673e5d0cd3",
          "sha256": "12c7f5b89c94a0b88f21ba4828124664c70d4dd4b8c72c09f92c9e71d58b7b30",
          "sha1": "ca02085d010c9fcbf1114e5d3b35c7e22844255f",
          "md5": "b2faafa9f5bd700976f13a1f0038a163"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "apollo-engine-ktor-kotlin-0.1.2-SNAPSHOT-sources.jar",
          "url": "apollo-engine-ktor-0.1.2-SNAPSHOT-sources.jar",
          "size": 6967,
          "sha512": "44c54ed50185b99ec2e9cc98a1e02f7b7c08462071b998537dd9d982eb3b92de8413d992aa7fee7360436d5a5bc46bbb174a4f22980be0e90edbf957c37ea493",
          "sha256": "8e8e758403eba17fece6ed5e2b94f37acca1cf5ba52f57522bb34af95adb26e1",
          "sha1": "47881525c98ec01f4b4858fc21fa0547572492e1",
          "md5": "5df6de5fa6dbbfb89d8971d09e73c378"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../apollo-engine-ktor-iosarm64/0.1.2-SNAPSHOT/apollo-engine-ktor-iosarm64-0.1.2-SNAPSHOT.module",
        "group": "com.apollographql.ktor",
        "module": "apollo-engine-ktor-iosarm64",
        "version": "0.1.2-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../apollo-engine-ktor-iosarm64/0.1.2-SNAPSHOT/apollo-engine-ktor-iosarm64-0.1.2-SNAPSHOT.module",
        "group": "com.apollographql.ktor",
        "module": "apollo-engine-ktor-iosarm64",
        "version": "0.1.2-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../apollo-engine-ktor-iosarm64/0.1.2-SNAPSHOT/apollo-engine-ktor-iosarm64-0.1.2-SNAPSHOT.module",
        "group": "com.apollographql.ktor",
        "module": "apollo-engine-ktor-iosarm64",
        "version": "0.1.2-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../apollo-engine-ktor-iossimulatorarm64/0.1.2-SNAPSHOT/apollo-engine-ktor-iossimulatorarm64-0.1.2-SNAPSHOT.module",
        "group": "com.apollographql.ktor",
        "module": "apollo-engine-ktor-iossimulatorarm64",
        "version": "0.1.2-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../apollo-engine-ktor-iossimulatorarm64/0.1.2-SNAPSHOT/apollo-engine-ktor-iossimulatorarm64-0.1.2-SNAPSHOT.module",
        "group": "com.apollographql.ktor",
        "module": "apollo-engine-ktor-iossimulatorarm64",
        "version": "0.1.2-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../apollo-engine-ktor-iossimulatorarm64/0.1.2-SNAPSHOT/apollo-engine-ktor-iossimulatorarm64-0.1.2-SNAPSHOT.module",
        "group": "com.apollographql.ktor",
        "module": "apollo-engine-ktor-iossimulatorarm64",
        "version": "0.1.2-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../apollo-engine-ktor-iosx64/0.1.2-SNAPSHOT/apollo-engine-ktor-iosx64-0.1.2-SNAPSHOT.module",
        "group": "com.apollographql.ktor",
        "module": "apollo-engine-ktor-iosx64",
        "version": "0.1.2-SNAPSHOT"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../apollo-engine-ktor-iosx64/0.1.2-SNAPSHOT/apollo-engine-ktor-iosx64-0.1.2-SNAPSHOT.module",
        "group": "com.apollographql.ktor",
        "module": "apollo-engine-ktor-iosx64",
        "version": "0.1.2-SNAPSHOT"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../apollo-engine-ktor-iosx64/0.1.2-SNAPSHOT/apollo-engine-ktor-iosx64-0.1.2-SNAPSHOT.module",
        "group": "com.apollographql.ktor",
        "module": "apollo-engine-ktor-iosx64",
        "version": "0.1.2-SNAPSHOT"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../apollo-engine-ktor-js/0.1.2-SNAPSHOT/apollo-engine-ktor-js-0.1.2-SNAPSHOT.module",
        "group": "com.apollographql.ktor",
        "module": "apollo-engine-ktor-js",
        "version": "0.1.2-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../apollo-engine-ktor-js/0.1.2-SNAPSHOT/apollo-engine-ktor-js-0.1.2-SNAPSHOT.module",
        "group": "com.apollographql.ktor",
        "module": "apollo-engine-ktor-js",
        "version": "0.1.2-SNAPSHOT"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../apollo-engine-ktor-js/0.1.2-SNAPSHOT/apollo-engine-ktor-js-0.1.2-SNAPSHOT.module",
        "group": "com.apollographql.ktor",
        "module": "apollo-engine-ktor-js",
        "version": "0.1.2-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../apollo-engine-ktor-jvm/0.1.2-SNAPSHOT/apollo-engine-ktor-jvm-0.1.2-SNAPSHOT.module",
        "group": "com.apollographql.ktor",
        "module": "apollo-engine-ktor-jvm",
        "version": "0.1.2-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../apollo-engine-ktor-jvm/0.1.2-SNAPSHOT/apollo-engine-ktor-jvm-0.1.2-SNAPSHOT.module",
        "group": "com.apollographql.ktor",
        "module": "apollo-engine-ktor-jvm",
        "version": "0.1.2-SNAPSHOT"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../apollo-engine-ktor-jvm/0.1.2-SNAPSHOT/apollo-engine-ktor-jvm-0.1.2-SNAPSHOT.module",
        "group": "com.apollographql.ktor",
        "module": "apollo-engine-ktor-jvm",
        "version": "0.1.2-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../apollo-engine-ktor-macosarm64/0.1.2-SNAPSHOT/apollo-engine-ktor-macosarm64-0.1.2-SNAPSHOT.module",
        "group": "com.apollographql.ktor",
        "module": "apollo-engine-ktor-macosarm64",
        "version": "0.1.2-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../apollo-engine-ktor-macosarm64/0.1.2-SNAPSHOT/apollo-engine-ktor-macosarm64-0.1.2-SNAPSHOT.module",
        "group": "com.apollographql.ktor",
        "module": "apollo-engine-ktor-macosarm64",
        "version": "0.1.2-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../apollo-engine-ktor-macosarm64/0.1.2-SNAPSHOT/apollo-engine-ktor-macosarm64-0.1.2-SNAPSHOT.module",
        "group": "com.apollographql.ktor",
        "module": "apollo-engine-ktor-macosarm64",
        "version": "0.1.2-SNAPSHOT"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../apollo-engine-ktor-macosx64/0.1.2-SNAPSHOT/apollo-engine-ktor-macosx64-0.1.2-SNAPSHOT.module",
        "group": "com.apollographql.ktor",
        "module": "apollo-engine-ktor-macosx64",
        "version": "0.1.2-SNAPSHOT"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../apollo-engine-ktor-macosx64/0.1.2-SNAPSHOT/apollo-engine-ktor-macosx64-0.1.2-SNAPSHOT.module",
        "group": "com.apollographql.ktor",
        "module": "apollo-engine-ktor-macosx64",
        "version": "0.1.2-SNAPSHOT"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../apollo-engine-ktor-macosx64/0.1.2-SNAPSHOT/apollo-engine-ktor-macosx64-0.1.2-SNAPSHOT.module",
        "group": "com.apollographql.ktor",
        "module": "apollo-engine-ktor-macosx64",
        "version": "0.1.2-SNAPSHOT"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../apollo-engine-ktor-tvosarm64/0.1.2-SNAPSHOT/apollo-engine-ktor-tvosarm64-0.1.2-SNAPSHOT.module",
        "group": "com.apollographql.ktor",
        "module": "apollo-engine-ktor-tvosarm64",
        "version": "0.1.2-SNAPSHOT"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../apollo-engine-ktor-tvosarm64/0.1.2-SNAPSHOT/apollo-engine-ktor-tvosarm64-0.1.2-SNAPSHOT.module",
        "group": "com.apollographql.ktor",
        "module": "apollo-engine-ktor-tvosarm64",
        "version": "0.1.2-SNAPSHOT"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../apollo-engine-ktor-tvosarm64/0.1.2-SNAPSHOT/apollo-engine-ktor-tvosarm64-0.1.2-SNAPSHOT.module",
        "group": "com.apollographql.ktor",
        "module": "apollo-engine-ktor-tvosarm64",
        "version": "0.1.2-SNAPSHOT"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../apollo-engine-ktor-tvossimulatorarm64/0.1.2-SNAPSHOT/apollo-engine-ktor-tvossimulatorarm64-0.1.2-SNAPSHOT.module",
        "group": "com.apollographql.ktor",
        "module": "apollo-engine-ktor-tvossimulatorarm64",
        "version": "0.1.2-SNAPSHOT"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../apollo-engine-ktor-tvossimulatorarm64/0.1.2-SNAPSHOT/apollo-engine-ktor-tvossimulatorarm64-0.1.2-SNAPSHOT.module",
        "group": "com.apollographql.ktor",
        "module": "apollo-engine-ktor-tvossimulatorarm64",
        "version": "0.1.2-SNAPSHOT"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../apollo-engine-ktor-tvossimulatorarm64/0.1.2-SNAPSHOT/apollo-engine-ktor-tvossimulatorarm64-0.1.2-SNAPSHOT.module",
        "group": "com.apollographql.ktor",
        "module": "apollo-engine-ktor-tvossimulatorarm64",
        "version": "0.1.2-SNAPSHOT"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../apollo-engine-ktor-tvosx64/0.1.2-SNAPSHOT/apollo-engine-ktor-tvosx64-0.1.2-SNAPSHOT.module",
        "group": "com.apollographql.ktor",
        "module": "apollo-engine-ktor-tvosx64",
        "version": "0.1.2-SNAPSHOT"
      }
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../apollo-engine-ktor-tvosx64/0.1.2-SNAPSHOT/apollo-engine-ktor-tvosx64-0.1.2-SNAPSHOT.module",
        "group": "com.apollographql.ktor",
        "module": "apollo-engine-ktor-tvosx64",
        "version": "0.1.2-SNAPSHOT"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../apollo-engine-ktor-tvosx64/0.1.2-SNAPSHOT/apollo-engine-ktor-tvosx64-0.1.2-SNAPSHOT.module",
        "group": "com.apollographql.ktor",
        "module": "apollo-engine-ktor-tvosx64",
        "version": "0.1.2-SNAPSHOT"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../apollo-engine-ktor-wasm-js/0.1.2-SNAPSHOT/apollo-engine-ktor-wasm-js-0.1.2-SNAPSHOT.module",
        "group": "com.apollographql.ktor",
        "module": "apollo-engine-ktor-wasm-js",
        "version": "0.1.2-SNAPSHOT"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../apollo-engine-ktor-wasm-js/0.1.2-SNAPSHOT/apollo-engine-ktor-wasm-js-0.1.2-SNAPSHOT.module",
        "group": "com.apollographql.ktor",
        "module": "apollo-engine-ktor-wasm-js",
        "version": "0.1.2-SNAPSHOT"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../apollo-engine-ktor-wasm-js/0.1.2-SNAPSHOT/apollo-engine-ktor-wasm-js-0.1.2-SNAPSHOT.module",
        "group": "com.apollographql.ktor",
        "module": "apollo-engine-ktor-wasm-js",
        "version": "0.1.2-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../apollo-engine-ktor-watchosarm32/0.1.2-SNAPSHOT/apollo-engine-ktor-watchosarm32-0.1.2-SNAPSHOT.module",
        "group": "com.apollographql.ktor",
        "module": "apollo-engine-ktor-watchosarm32",
        "version": "0.1.2-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../apollo-engine-ktor-watchosarm32/0.1.2-SNAPSHOT/apollo-engine-ktor-watchosarm32-0.1.2-SNAPSHOT.module",
        "group": "com.apollographql.ktor",
        "module": "apollo-engine-ktor-watchosarm32",
        "version": "0.1.2-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../apollo-engine-ktor-watchosarm32/0.1.2-SNAPSHOT/apollo-engine-ktor-watchosarm32-0.1.2-SNAPSHOT.module",
        "group": "com.apollographql.ktor",
        "module": "apollo-engine-ktor-watchosarm32",
        "version": "0.1.2-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../apollo-engine-ktor-watchosarm64/0.1.2-SNAPSHOT/apollo-engine-ktor-watchosarm64-0.1.2-SNAPSHOT.module",
        "group": "com.apollographql.ktor",
        "module": "apollo-engine-ktor-watchosarm64",
        "version": "0.1.2-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../apollo-engine-ktor-watchosarm64/0.1.2-SNAPSHOT/apollo-engine-ktor-watchosarm64-0.1.2-SNAPSHOT.module",
        "group": "com.apollographql.ktor",
        "module": "apollo-engine-ktor-watchosarm64",
        "version": "0.1.2-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../apollo-engine-ktor-watchosarm64/0.1.2-SNAPSHOT/apollo-engine-ktor-watchosarm64-0.1.2-SNAPSHOT.module",
        "group": "com.apollographql.ktor",
        "module": "apollo-engine-ktor-watchosarm64",
        "version": "0.1.2-SNAPSHOT"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../apollo-engine-ktor-watchossimulatorarm64/0.1.2-SNAPSHOT/apollo-engine-ktor-watchossimulatorarm64-0.1.2-SNAPSHOT.module",
        "group": "com.apollographql.ktor",
        "module": "apollo-engine-ktor-watchossimulatorarm64",
        "version": "0.1.2-SNAPSHOT"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../apollo-engine-ktor-watchossimulatorarm64/0.1.2-SNAPSHOT/apollo-engine-ktor-watchossimulatorarm64-0.1.2-SNAPSHOT.module",
        "group": "com.apollographql.ktor",
        "module": "apollo-engine-ktor-watchossimulatorarm64",
        "version": "0.1.2-SNAPSHOT"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../apollo-engine-ktor-watchossimulatorarm64/0.1.2-SNAPSHOT/apollo-engine-ktor-watchossimulatorarm64-0.1.2-SNAPSHOT.module",
        "group": "com.apollographql.ktor",
        "module": "apollo-engine-ktor-watchossimulatorarm64",
        "version": "0.1.2-SNAPSHOT"
      }
    }
  ]
}
