{
  "formatVersion": "1.1",
  "component": {
    "url": "../../apollo-engine-ktor/0.1.1-SNAPSHOT/apollo-engine-ktor-0.1.1-SNAPSHOT.module",
    "group": "com.apollographql.ktor",
    "module": "apollo-engine-ktor",
    "version": "0.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.apollographql.apollo",
          "module": "apollo-runtime",
          "version": {
            "requires": "4.1.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-websockets",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "apollo-engine-ktor-js-0.1.1-SNAPSHOT.klib",
          "url": "apollo-engine-ktor-js-0.1.1-SNAPSHOT.klib",
          "size": 22732,
          "sha512": "21957703da28be5cc9694ec8d21fccd7b5bc080abfe0241e7f5d57b849c34b127876f6715e5c87004a219fbb70bc54cce8893b3d94fbab4ca8bdd096253c8035",
          "sha256": "9442831374e145c85cdff252796d4fc676178f24180b2c1baac0fdfd91eb10ad",
          "sha1": "fff31415be60a363c90eb164c9f2a11966184625",
          "md5": "70688c32018f5ee0d4b3f334db36ed68"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.apollographql.apollo",
          "module": "apollo-runtime",
          "version": {
            "requires": "4.1.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-websockets",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "apollo-engine-ktor-js-0.1.1-SNAPSHOT.klib",
          "url": "apollo-engine-ktor-js-0.1.1-SNAPSHOT.klib",
          "size": 22732,
          "sha512": "21957703da28be5cc9694ec8d21fccd7b5bc080abfe0241e7f5d57b849c34b127876f6715e5c87004a219fbb70bc54cce8893b3d94fbab4ca8bdd096253c8035",
          "sha256": "9442831374e145c85cdff252796d4fc676178f24180b2c1baac0fdfd91eb10ad",
          "sha1": "fff31415be60a363c90eb164c9f2a11966184625",
          "md5": "70688c32018f5ee0d4b3f334db36ed68"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "apollo-engine-ktor-js-0.1.1-SNAPSHOT-sources.jar",
          "url": "apollo-engine-ktor-js-0.1.1-SNAPSHOT-sources.jar",
          "size": 5925,
          "sha512": "3a3c61f3534dc195b7f35d72769d7f32d0216818397a473cdc73fac44dd9690b6371f6a601030882302ec3aaba0c6f4c49b4e1f4b3d823f058d0b811143fdec4",
          "sha256": "75dcba0b6d200de6d168fa80256f8eaa187daf0f83057aab0f785e9fad7e575c",
          "sha1": "ede96e87b9214745faa1ed77fa8ab39e500ff7be",
          "md5": "27c9ab0459a3f0ae4af3e10cd84851fc"
        }
      ]
    }
  ]
}
