{
  "formatVersion": "1.1",
  "component": {
    "url": "../../apollo-engine-ktor/0.1.1-SNAPSHOT/apollo-engine-ktor-0.1.1-SNAPSHOT.module",
    "group": "com.apollographql.ktor",
    "module": "apollo-engine-ktor",
    "version": "0.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.apollographql.apollo",
          "module": "apollo-runtime",
          "version": {
            "requires": "4.1.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-websockets",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "apollo-engine-ktor-jvm-0.1.1-SNAPSHOT.jar",
          "url": "apollo-engine-ktor-jvm-0.1.1-SNAPSHOT.jar",
          "size": 30739,
          "sha512": "32e9e09a256699ba84548f95cd48e82e28581cbeacf41c7009a86dfec38c564369b9fd49faad87164229772d5b79e24b0ce4a8b627bcd82d34f8fa9668793ffe",
          "sha256": "4064e3fc2cc0ee9d53344eae8efa3c4e48f2bd4b1c2f45f4ebaf88de26010d11",
          "sha1": "c76f3fe8bd02fdecadd7ef973cbbe9ed96f0cf27",
          "md5": "b83339be76795a66c8bae569df6b1dd5"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.apollographql.apollo",
          "module": "apollo-runtime",
          "version": {
            "requires": "4.1.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-websockets",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "apollo-engine-ktor-jvm-0.1.1-SNAPSHOT.jar",
          "url": "apollo-engine-ktor-jvm-0.1.1-SNAPSHOT.jar",
          "size": 30739,
          "sha512": "32e9e09a256699ba84548f95cd48e82e28581cbeacf41c7009a86dfec38c564369b9fd49faad87164229772d5b79e24b0ce4a8b627bcd82d34f8fa9668793ffe",
          "sha256": "4064e3fc2cc0ee9d53344eae8efa3c4e48f2bd4b1c2f45f4ebaf88de26010d11",
          "sha1": "c76f3fe8bd02fdecadd7ef973cbbe9ed96f0cf27",
          "md5": "b83339be76795a66c8bae569df6b1dd5"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "apollo-engine-ktor-jvm-0.1.1-SNAPSHOT-sources.jar",
          "url": "apollo-engine-ktor-jvm-0.1.1-SNAPSHOT-sources.jar",
          "size": 5904,
          "sha512": "fc278b70cdd238a77588072b4b1cd5a5b46ec7d99b2bc97ea1c47bf298f4f5aa98e7b1c2ae5da99398396d0e81304e50a8030471d1a4b53523702d999214e48c",
          "sha256": "6cdf6b8cc6c0795de3ebd3c8fe8379512a33c9bf39fff9e8a4b5a21728de5f33",
          "sha1": "a7ba66744df97e2878114a554be8a41b040274ed",
          "md5": "f5200b33f4a62b9a1e6b94bceae65bda"
        }
      ]
    }
  ]
}
