{
  "formatVersion": "1.1",
  "component": {
    "url": "../../apollo-engine-ktor/0.1.2-SNAPSHOT/apollo-engine-ktor-0.1.2-SNAPSHOT.module",
    "group": "com.apollographql.ktor",
    "module": "apollo-engine-ktor",
    "version": "0.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.apollographql.apollo",
          "module": "apollo-runtime",
          "version": {
            "requires": "5.0.0-alpha.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-websockets",
          "version": {
            "requires": "3.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "apollo-engine-ktor-wasm-js-0.1.2-SNAPSHOT.klib",
          "url": "apollo-engine-ktor-wasm-js-0.1.2-SNAPSHOT.klib",
          "size": 28856,
          "sha512": "aafae10aa86b84b41ad87f811e9c73f7a426edc4b38e6e3937384d31a12156ebbd26446d34881d90006c3aafce5443246b309af0e7fb6af33be8c5f1521336ba",
          "sha256": "b72d8bd5f49596ff1fef4562d44e63485e2658455ee68d06278a206cfd281b93",
          "sha1": "f9ce0ccd36aa85d2182d17d1ecfe6b928b650eb3",
          "md5": "82c0c373be84a066ce695970112081e1"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.apollographql.apollo",
          "module": "apollo-runtime",
          "version": {
            "requires": "5.0.0-alpha.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-websockets",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "apollo-engine-ktor-wasm-js-0.1.2-SNAPSHOT.klib",
          "url": "apollo-engine-ktor-wasm-js-0.1.2-SNAPSHOT.klib",
          "size": 28856,
          "sha512": "aafae10aa86b84b41ad87f811e9c73f7a426edc4b38e6e3937384d31a12156ebbd26446d34881d90006c3aafce5443246b309af0e7fb6af33be8c5f1521336ba",
          "sha256": "b72d8bd5f49596ff1fef4562d44e63485e2658455ee68d06278a206cfd281b93",
          "sha1": "f9ce0ccd36aa85d2182d17d1ecfe6b928b650eb3",
          "md5": "82c0c373be84a066ce695970112081e1"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "apollo-engine-ktor-wasm-js-0.1.2-SNAPSHOT-sources.jar",
          "url": "apollo-engine-ktor-wasm-js-0.1.2-SNAPSHOT-sources.jar",
          "size": 7717,
          "sha512": "a057c42966d288f437199db8b780e8fdb9735c19978838abb7b38dba3c948d61e4945dd032ad089575fbbfc690f2ff87cfb3cf26dd6721cf7b82d59f7f6f4400",
          "sha256": "2f4a365c57842eb3c46a160a41441c99b52b44906440cafc5ced9f6f5c818647",
          "sha1": "e44f5118c5fb8970bc91c15cde7a5c4df586f829",
          "md5": "bcf1dd91b9acf598f3bf7d5b29505fed"
        }
      ]
    }
  ]
}
