{
  "formatVersion": "1.1",
  "component": {
    "url": "../../apollo-engine-ktor/1.0.0-alpha.0/apollo-engine-ktor-1.0.0-alpha.0.module",
    "group": "com.apollographql.ktor",
    "module": "apollo-engine-ktor",
    "version": "1.0.0-alpha.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.apollographql.apollo",
          "module": "apollo-runtime",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-websockets",
          "version": {
            "requires": "3.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "apollo-engine-ktor-wasm-js-1.0.0-alpha.0.klib",
          "url": "apollo-engine-ktor-wasm-js-1.0.0-alpha.0.klib",
          "size": 26316,
          "sha512": "c4be8416f577c801eb3508200bcddc9b0862971f75f3180073710d0f0d5719b687b5ad08a9444a797dc67c05374ea9cab6d135e04cc83ce09c9707b59981f145",
          "sha256": "6b20eb3cd5552ce10e6dbc08c425a8d1c9f8be108790bbe78d033c082ec67ee1",
          "sha1": "64442e86cbe8f6c62c74dbbbce2d55edb05e4d03",
          "md5": "863674e3c2d34cc4eda97cb9f0c515b8"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.apollographql.apollo",
          "module": "apollo-runtime",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-websockets",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "apollo-engine-ktor-wasm-js-1.0.0-alpha.0.klib",
          "url": "apollo-engine-ktor-wasm-js-1.0.0-alpha.0.klib",
          "size": 26316,
          "sha512": "c4be8416f577c801eb3508200bcddc9b0862971f75f3180073710d0f0d5719b687b5ad08a9444a797dc67c05374ea9cab6d135e04cc83ce09c9707b59981f145",
          "sha256": "6b20eb3cd5552ce10e6dbc08c425a8d1c9f8be108790bbe78d033c082ec67ee1",
          "sha1": "64442e86cbe8f6c62c74dbbbce2d55edb05e4d03",
          "md5": "863674e3c2d34cc4eda97cb9f0c515b8"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "apollo-engine-ktor-wasm-js-1.0.0-alpha.0-sources.jar",
          "url": "apollo-engine-ktor-wasm-js-1.0.0-alpha.0-sources.jar",
          "size": 7717,
          "sha512": "a057c42966d288f437199db8b780e8fdb9735c19978838abb7b38dba3c948d61e4945dd032ad089575fbbfc690f2ff87cfb3cf26dd6721cf7b82d59f7f6f4400",
          "sha256": "2f4a365c57842eb3c46a160a41441c99b52b44906440cafc5ced9f6f5c818647",
          "sha1": "e44f5118c5fb8970bc91c15cde7a5c4df586f829",
          "md5": "bcf1dd91b9acf598f3bf7d5b29505fed"
        }
      ]
    }
  ]
}
