{
  "formatVersion": "1.1",
  "component": {
    "group": "com.apollographql.ktor",
    "module": "apollo-engine-ktor",
    "version": "0.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "com.apollographql.apollo",
          "module": "apollo-runtime",
          "version": {
            "requires": "4.1.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-websockets",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "apollo-engine-ktor-metadata-0.1.1-SNAPSHOT.jar",
          "url": "apollo-engine-ktor-0.1.1-SNAPSHOT.jar",
          "size": 6957,
          "sha512": "0c88ca8ede2f4c58a630cad8061968ba92f6527c2f09bd1c963eea2674ccb3b3dc5405b7df858d3b6a66216a1e79ff4ebaa3a60909eda476554bce4b6652e9a0",
          "sha256": "98d7dacc7abf1ce80b51e5d3c0bee6536d49f5a8e94b85af483eee62abd61e89",
          "sha1": "16f02bf05e33401a1035db253ec198738607a091",
          "md5": "ec9f6e54570e0dcf497c7d5599566c0f"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "apollo-engine-ktor-kotlin-0.1.1-SNAPSHOT-sources.jar",
          "url": "apollo-engine-ktor-0.1.1-SNAPSHOT-sources.jar",
          "size": 5904,
          "sha512": "c77cde7cae63b7bbf5b14fce88ad954a782dad7bca9bd1022db0e79299dc6774debd8d3918a803468c9e15360371dce0fd8da5f80cbf836e9e7457a83b708888",
          "sha256": "7dac1830bec7222568db63ea5c357e4546e91b079d56c4b57d253345ddab7bcd",
          "sha1": "4d7d0d345da7a9fab6ea2c611044cdf3b8aed638",
          "md5": "917ba51f824801dbc08a7a11e5c4e78c"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../apollo-engine-ktor-iosarm64/0.1.1-SNAPSHOT/apollo-engine-ktor-iosarm64-0.1.1-SNAPSHOT.module",
        "group": "com.apollographql.ktor",
        "module": "apollo-engine-ktor-iosarm64",
        "version": "0.1.1-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../apollo-engine-ktor-iosarm64/0.1.1-SNAPSHOT/apollo-engine-ktor-iosarm64-0.1.1-SNAPSHOT.module",
        "group": "com.apollographql.ktor",
        "module": "apollo-engine-ktor-iosarm64",
        "version": "0.1.1-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../apollo-engine-ktor-iosarm64/0.1.1-SNAPSHOT/apollo-engine-ktor-iosarm64-0.1.1-SNAPSHOT.module",
        "group": "com.apollographql.ktor",
        "module": "apollo-engine-ktor-iosarm64",
        "version": "0.1.1-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../apollo-engine-ktor-iossimulatorarm64/0.1.1-SNAPSHOT/apollo-engine-ktor-iossimulatorarm64-0.1.1-SNAPSHOT.module",
        "group": "com.apollographql.ktor",
        "module": "apollo-engine-ktor-iossimulatorarm64",
        "version": "0.1.1-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../apollo-engine-ktor-iossimulatorarm64/0.1.1-SNAPSHOT/apollo-engine-ktor-iossimulatorarm64-0.1.1-SNAPSHOT.module",
        "group": "com.apollographql.ktor",
        "module": "apollo-engine-ktor-iossimulatorarm64",
        "version": "0.1.1-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../apollo-engine-ktor-iossimulatorarm64/0.1.1-SNAPSHOT/apollo-engine-ktor-iossimulatorarm64-0.1.1-SNAPSHOT.module",
        "group": "com.apollographql.ktor",
        "module": "apollo-engine-ktor-iossimulatorarm64",
        "version": "0.1.1-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../apollo-engine-ktor-iosx64/0.1.1-SNAPSHOT/apollo-engine-ktor-iosx64-0.1.1-SNAPSHOT.module",
        "group": "com.apollographql.ktor",
        "module": "apollo-engine-ktor-iosx64",
        "version": "0.1.1-SNAPSHOT"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../apollo-engine-ktor-iosx64/0.1.1-SNAPSHOT/apollo-engine-ktor-iosx64-0.1.1-SNAPSHOT.module",
        "group": "com.apollographql.ktor",
        "module": "apollo-engine-ktor-iosx64",
        "version": "0.1.1-SNAPSHOT"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../apollo-engine-ktor-iosx64/0.1.1-SNAPSHOT/apollo-engine-ktor-iosx64-0.1.1-SNAPSHOT.module",
        "group": "com.apollographql.ktor",
        "module": "apollo-engine-ktor-iosx64",
        "version": "0.1.1-SNAPSHOT"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../apollo-engine-ktor-js/0.1.1-SNAPSHOT/apollo-engine-ktor-js-0.1.1-SNAPSHOT.module",
        "group": "com.apollographql.ktor",
        "module": "apollo-engine-ktor-js",
        "version": "0.1.1-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../apollo-engine-ktor-js/0.1.1-SNAPSHOT/apollo-engine-ktor-js-0.1.1-SNAPSHOT.module",
        "group": "com.apollographql.ktor",
        "module": "apollo-engine-ktor-js",
        "version": "0.1.1-SNAPSHOT"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../apollo-engine-ktor-js/0.1.1-SNAPSHOT/apollo-engine-ktor-js-0.1.1-SNAPSHOT.module",
        "group": "com.apollographql.ktor",
        "module": "apollo-engine-ktor-js",
        "version": "0.1.1-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../apollo-engine-ktor-jvm/0.1.1-SNAPSHOT/apollo-engine-ktor-jvm-0.1.1-SNAPSHOT.module",
        "group": "com.apollographql.ktor",
        "module": "apollo-engine-ktor-jvm",
        "version": "0.1.1-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../apollo-engine-ktor-jvm/0.1.1-SNAPSHOT/apollo-engine-ktor-jvm-0.1.1-SNAPSHOT.module",
        "group": "com.apollographql.ktor",
        "module": "apollo-engine-ktor-jvm",
        "version": "0.1.1-SNAPSHOT"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../apollo-engine-ktor-jvm/0.1.1-SNAPSHOT/apollo-engine-ktor-jvm-0.1.1-SNAPSHOT.module",
        "group": "com.apollographql.ktor",
        "module": "apollo-engine-ktor-jvm",
        "version": "0.1.1-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../apollo-engine-ktor-macosarm64/0.1.1-SNAPSHOT/apollo-engine-ktor-macosarm64-0.1.1-SNAPSHOT.module",
        "group": "com.apollographql.ktor",
        "module": "apollo-engine-ktor-macosarm64",
        "version": "0.1.1-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../apollo-engine-ktor-macosarm64/0.1.1-SNAPSHOT/apollo-engine-ktor-macosarm64-0.1.1-SNAPSHOT.module",
        "group": "com.apollographql.ktor",
        "module": "apollo-engine-ktor-macosarm64",
        "version": "0.1.1-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../apollo-engine-ktor-macosarm64/0.1.1-SNAPSHOT/apollo-engine-ktor-macosarm64-0.1.1-SNAPSHOT.module",
        "group": "com.apollographql.ktor",
        "module": "apollo-engine-ktor-macosarm64",
        "version": "0.1.1-SNAPSHOT"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../apollo-engine-ktor-macosx64/0.1.1-SNAPSHOT/apollo-engine-ktor-macosx64-0.1.1-SNAPSHOT.module",
        "group": "com.apollographql.ktor",
        "module": "apollo-engine-ktor-macosx64",
        "version": "0.1.1-SNAPSHOT"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../apollo-engine-ktor-macosx64/0.1.1-SNAPSHOT/apollo-engine-ktor-macosx64-0.1.1-SNAPSHOT.module",
        "group": "com.apollographql.ktor",
        "module": "apollo-engine-ktor-macosx64",
        "version": "0.1.1-SNAPSHOT"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../apollo-engine-ktor-macosx64/0.1.1-SNAPSHOT/apollo-engine-ktor-macosx64-0.1.1-SNAPSHOT.module",
        "group": "com.apollographql.ktor",
        "module": "apollo-engine-ktor-macosx64",
        "version": "0.1.1-SNAPSHOT"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../apollo-engine-ktor-tvosarm64/0.1.1-SNAPSHOT/apollo-engine-ktor-tvosarm64-0.1.1-SNAPSHOT.module",
        "group": "com.apollographql.ktor",
        "module": "apollo-engine-ktor-tvosarm64",
        "version": "0.1.1-SNAPSHOT"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../apollo-engine-ktor-tvosarm64/0.1.1-SNAPSHOT/apollo-engine-ktor-tvosarm64-0.1.1-SNAPSHOT.module",
        "group": "com.apollographql.ktor",
        "module": "apollo-engine-ktor-tvosarm64",
        "version": "0.1.1-SNAPSHOT"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../apollo-engine-ktor-tvosarm64/0.1.1-SNAPSHOT/apollo-engine-ktor-tvosarm64-0.1.1-SNAPSHOT.module",
        "group": "com.apollographql.ktor",
        "module": "apollo-engine-ktor-tvosarm64",
        "version": "0.1.1-SNAPSHOT"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../apollo-engine-ktor-tvossimulatorarm64/0.1.1-SNAPSHOT/apollo-engine-ktor-tvossimulatorarm64-0.1.1-SNAPSHOT.module",
        "group": "com.apollographql.ktor",
        "module": "apollo-engine-ktor-tvossimulatorarm64",
        "version": "0.1.1-SNAPSHOT"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../apollo-engine-ktor-tvossimulatorarm64/0.1.1-SNAPSHOT/apollo-engine-ktor-tvossimulatorarm64-0.1.1-SNAPSHOT.module",
        "group": "com.apollographql.ktor",
        "module": "apollo-engine-ktor-tvossimulatorarm64",
        "version": "0.1.1-SNAPSHOT"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../apollo-engine-ktor-tvossimulatorarm64/0.1.1-SNAPSHOT/apollo-engine-ktor-tvossimulatorarm64-0.1.1-SNAPSHOT.module",
        "group": "com.apollographql.ktor",
        "module": "apollo-engine-ktor-tvossimulatorarm64",
        "version": "0.1.1-SNAPSHOT"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../apollo-engine-ktor-tvosx64/0.1.1-SNAPSHOT/apollo-engine-ktor-tvosx64-0.1.1-SNAPSHOT.module",
        "group": "com.apollographql.ktor",
        "module": "apollo-engine-ktor-tvosx64",
        "version": "0.1.1-SNAPSHOT"
      }
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../apollo-engine-ktor-tvosx64/0.1.1-SNAPSHOT/apollo-engine-ktor-tvosx64-0.1.1-SNAPSHOT.module",
        "group": "com.apollographql.ktor",
        "module": "apollo-engine-ktor-tvosx64",
        "version": "0.1.1-SNAPSHOT"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../apollo-engine-ktor-tvosx64/0.1.1-SNAPSHOT/apollo-engine-ktor-tvosx64-0.1.1-SNAPSHOT.module",
        "group": "com.apollographql.ktor",
        "module": "apollo-engine-ktor-tvosx64",
        "version": "0.1.1-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../apollo-engine-ktor-watchosarm32/0.1.1-SNAPSHOT/apollo-engine-ktor-watchosarm32-0.1.1-SNAPSHOT.module",
        "group": "com.apollographql.ktor",
        "module": "apollo-engine-ktor-watchosarm32",
        "version": "0.1.1-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../apollo-engine-ktor-watchosarm32/0.1.1-SNAPSHOT/apollo-engine-ktor-watchosarm32-0.1.1-SNAPSHOT.module",
        "group": "com.apollographql.ktor",
        "module": "apollo-engine-ktor-watchosarm32",
        "version": "0.1.1-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../apollo-engine-ktor-watchosarm32/0.1.1-SNAPSHOT/apollo-engine-ktor-watchosarm32-0.1.1-SNAPSHOT.module",
        "group": "com.apollographql.ktor",
        "module": "apollo-engine-ktor-watchosarm32",
        "version": "0.1.1-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../apollo-engine-ktor-watchosarm64/0.1.1-SNAPSHOT/apollo-engine-ktor-watchosarm64-0.1.1-SNAPSHOT.module",
        "group": "com.apollographql.ktor",
        "module": "apollo-engine-ktor-watchosarm64",
        "version": "0.1.1-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../apollo-engine-ktor-watchosarm64/0.1.1-SNAPSHOT/apollo-engine-ktor-watchosarm64-0.1.1-SNAPSHOT.module",
        "group": "com.apollographql.ktor",
        "module": "apollo-engine-ktor-watchosarm64",
        "version": "0.1.1-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../apollo-engine-ktor-watchosarm64/0.1.1-SNAPSHOT/apollo-engine-ktor-watchosarm64-0.1.1-SNAPSHOT.module",
        "group": "com.apollographql.ktor",
        "module": "apollo-engine-ktor-watchosarm64",
        "version": "0.1.1-SNAPSHOT"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../apollo-engine-ktor-watchossimulatorarm64/0.1.1-SNAPSHOT/apollo-engine-ktor-watchossimulatorarm64-0.1.1-SNAPSHOT.module",
        "group": "com.apollographql.ktor",
        "module": "apollo-engine-ktor-watchossimulatorarm64",
        "version": "0.1.1-SNAPSHOT"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../apollo-engine-ktor-watchossimulatorarm64/0.1.1-SNAPSHOT/apollo-engine-ktor-watchossimulatorarm64-0.1.1-SNAPSHOT.module",
        "group": "com.apollographql.ktor",
        "module": "apollo-engine-ktor-watchossimulatorarm64",
        "version": "0.1.1-SNAPSHOT"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../apollo-engine-ktor-watchossimulatorarm64/0.1.1-SNAPSHOT/apollo-engine-ktor-watchossimulatorarm64-0.1.1-SNAPSHOT.module",
        "group": "com.apollographql.ktor",
        "module": "apollo-engine-ktor-watchossimulatorarm64",
        "version": "0.1.1-SNAPSHOT"
      }
    }
  ]
}
