{
  "formatVersion": "1.1",
  "component": {
    "url": "../../apollo-engine-ktor/1.0.0-alpha.1-SNAPSHOT/apollo-engine-ktor-1.0.0-alpha.1-SNAPSHOT.module",
    "group": "com.apollographql.ktor",
    "module": "apollo-engine-ktor",
    "version": "1.0.0-alpha.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "com.apollographql.apollo",
          "module": "apollo-runtime",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-websockets",
          "version": {
            "requires": "3.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "apollo-engine-ktor-jvm-1.0.0-alpha.1-SNAPSHOT.jar",
          "url": "apollo-engine-ktor-jvm-1.0.0-alpha.1-SNAPSHOT.jar",
          "size": 49752,
          "sha512": "857229f996c65a484a7bd8b2bf8ada81eb7f941c58053488365af2b1f3014b0eb26e26be969040eb7399fd05c3d28c68f7978003300cb4f439944aaf59dd90f1",
          "sha256": "c59c67890fb9fe324eeed4dfd557c6da4f9ee599aa3034d7f58ba1f2ec4bdf98",
          "sha1": "a3bcff518af94125446735ef4ed5221177e14bf6",
          "md5": "89a5b1710f8db7c7a211df49672c4134"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "com.apollographql.apollo",
          "module": "apollo-runtime",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-websockets",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "apollo-engine-ktor-jvm-1.0.0-alpha.1-SNAPSHOT.jar",
          "url": "apollo-engine-ktor-jvm-1.0.0-alpha.1-SNAPSHOT.jar",
          "size": 49752,
          "sha512": "857229f996c65a484a7bd8b2bf8ada81eb7f941c58053488365af2b1f3014b0eb26e26be969040eb7399fd05c3d28c68f7978003300cb4f439944aaf59dd90f1",
          "sha256": "c59c67890fb9fe324eeed4dfd557c6da4f9ee599aa3034d7f58ba1f2ec4bdf98",
          "sha1": "a3bcff518af94125446735ef4ed5221177e14bf6",
          "md5": "89a5b1710f8db7c7a211df49672c4134"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "apollo-engine-ktor-jvm-1.0.0-alpha.1-SNAPSHOT-sources.jar",
          "url": "apollo-engine-ktor-jvm-1.0.0-alpha.1-SNAPSHOT-sources.jar",
          "size": 7696,
          "sha512": "253b5c8a119e5120aa17ecac772ad9e1063e3015e7f47975818f9e51c2c3e613dcdf6f567b89f0ed379b660a6849080dbef6c97fc67134be2798ed8c88184e1a",
          "sha256": "47e01af947873ac5a5cde7098bc2f0d48858aa3e9fc6b871ce109ec7099672ea",
          "sha1": "ef1603822acfc871fb3e3081c1926e57d866a8ef",
          "md5": "4d4bee2d9ad8ab2649ab6ea4f452711d"
        }
      ]
    }
  ]
}
